filebeat.inputs:
- type: log
  json.keys_under_root: true
  json.message_key: log
  enabled: true
  encoding: utf-8
  document_type: docker
  paths:
    - '/usr/share/docker/*/*.log'
processors:
- decode_json_fields:
    fields: ["log"]
    target: ""
    overwrite_keys: true
- add_docker_metadata: ~
 
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3
  
output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  template:
    name: "filebeat"
    path: "fields.yml"
    overwrite: false
  protocol: "http"

logging.to_files: true
logging.to_syslog: false